### ISSUE TITLE
CocoaPod is out of date

### ISSUE THREAD

**Issue by JDeokule** [square/objc-TimesSquare#47]
The CocoaPod was updated about 9 months ago while the last commit was 3 months ago.

I noticed at least 1 difference between the CocoaPod version and the master version here on Github.

For example, `- (void)scrollToDate:(NSDate *)date animated:(BOOL)animated;` is missing from the CocoaPod

**Comment by robertturrall** [comment]
Same here... makes the cocoa pod install pretty much unusable... could somebody please give a tip for what version number I could enter in the pod spec to get this to install the latest master version?

**Comment by dfed** [comment]
Working on tagging 1.0.2 now
