### ISSUE TITLE
Change Start Day

### ISSUE THREAD

**Issue by TamasRusvai** [square/objc-TimesSquare#68]
Hy,
I have to change the start day of a month. I want count the day from monday, or wednesday. How can i do this?

Thanks for your answer.

Update: Forgot built-in method :/

**Comment by SolveSoul** [comment]
Can you remember which built-in method you used? I cannot find the given method in the source code. Thanks in advance.

**Comment by TamasRusvai** [comment]
You can  change the built-in calendar, and change the new Calendar startDayofWeek. 

```
@property (nonatomic, strong) TSQCalendarView* mCalendarView;
@property (nonatomic, strong) NSCalendar* calendar;

self.calendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];
[self.calendar setFirstWeekday:[startdayofweek integerValue]];
self.mCalendarView.calendar = self.calendar;
```

[startdayofweek](https://developer.apple.com/reference/foundation/nscalendar/1408310-firstweekday)

Another method to use. I didn't tested, but i think it should work.

`[self.mCalendarView.calendar setFirstWeekday:[startdayofweek integerValue]];`

Hope it help you.

**Comment by SolveSoul** [comment]
That did the job, thanks a lot!
