### ISSUE TITLE
Change start day

### ISSUE THREAD

**Issue by Matic1911** [square/objc-TimesSquare#90]
I wan't to change start day from sunday to monday.

How can I do this?

**Comment by SolveSoul** [comment]
Have you find the solution for this problem? I'm still looking for a built-in method if any is available.

**Comment by MaticMale** [comment]
Sorry didn't find any. I used another solution that I found.

**Comment by SolveSoul** [comment]
Okay, thanks to let me know!

**Comment by SolveSoul** [comment]
In case you're still wondering, the solution can be found here: issue #68

**Comment by MaticMale** [comment]
Great that you solved the problem. Thank's for the solution!
